# Generated by Django 4.1.1 on 2022-09-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0013_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='cat',
        ),
    ]
